{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stac-fastapi-pgstac.secretName" . }}
  labels:
    {{- include "stac-fastapi-pgstac.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.usernameKey }}: {{ .Values.auth.username | b64enc | quote }}
  {{ .Values.auth.secretKeys.passwordKey }}: {{ required "auth.password is required unless auth.existingSecret is set" .Values.auth.password | b64enc | quote }}
{{- end }}
